// Agenchq/resources/js/components/dashboard/BackgroundCheckFormModal.vue
<template>
  <Dialog
    v-model:visible="dialogOpen"
    modal
    :header="`${isEdit ? 'Edit' : 'Add'} Background Check`"
    :style="{ width: 'min(900px, 95vw)' }"
    @hide="emit('close')"
  >
    <form class="space-y-4" @submit.prevent="submit">
      <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div class="space-y-2">
          <label class="text-xs font-bold uppercase tracking-widest text-[color:var(--p-text-muted-color)]">Candidate Name</label>
          <InputText v-model="form.candidate_name" class="w-full" required />
        </div>
        <div class="space-y-2">
          <label class="text-xs font-bold uppercase tracking-widest text-[color:var(--p-text-muted-color)]">Check Type</label>
          <Dropdown v-model="form.check_type" :options="checkTypeOptions" optionLabel="label" optionValue="value" class="w-full" />
        </div>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div class="space-y-2">
          <label class="text-xs font-bold uppercase tracking-widest text-[color:var(--p-text-muted-color)]">Issue Date</label>
          <InputText v-model="form.issue_date" type="date" class="w-full" />
        </div>
        <div class="space-y-2">
          <label class="text-xs font-bold uppercase tracking-widest text-[color:var(--p-text-muted-color)]">Expiry Date</label>
          <InputText v-model="form.expiry_date" type="date" class="w-full" />
        </div>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div class="space-y-2">
          <label class="text-xs font-bold uppercase tracking-widest text-[color:var(--p-text-muted-color)]">Verification Status</label>
          <Dropdown v-model="form.verification_status" :options="statusOptions" optionLabel="label" optionValue="value" class="w-full" />
        </div>
        <div class="space-y-2">
          <label class="text-xs font-bold uppercase tracking-widest text-[color:var(--p-text-muted-color)]">Document (optional)</label>
          <input type="file" class="block w-full" @change="onFileChange" />
        </div>
      </div>

      <div class="space-y-2">
        <label class="text-xs font-bold uppercase tracking-widest text-[color:var(--p-text-muted-color)]">Notes</label>
        <Textarea v-model="form.notes" rows="3" class="w-full" />
      </div>

      <Message v-if="formError" severity="error" :closable="false">{{ formError }}</Message>

      <div class="flex gap-2 justify-end pt-2">
        <Button type="button" label="Cancel" severity="secondary" outlined @click="emit('close')" />
        <Button type="submit" label="Save" :loading="saving" />
      </div>
    </form>
  </Dialog>
</template>

<script setup>
import axios from 'axios';
import { computed, ref, watch } from 'vue';
import Button from 'primevue/button';
import Dialog from 'primevue/dialog';
import Dropdown from 'primevue/dropdown';
import InputText from 'primevue/inputtext';
import Message from 'primevue/message';
import Textarea from 'primevue/textarea';

const props = defineProps({
    isOpen: { type: Boolean, required: true },
    initialData: { type: Object, default: null },
    selectedAdminId: { type: String, default: '' },
    attachUserId: { type: Boolean, default: false },
});

const emit = defineEmits(['close', 'success']);

const saving = ref(false);
const formError = ref('');
const documentFile = ref(null);

const form = ref({
    candidate_name: '',
    check_type: 'criminal_record_check',
    issue_date: '',
    expiry_date: '',
    verification_status: 'pending',
    notes: '',
});

const isEdit = computed(() => Boolean(props.initialData && props.initialData.id));

const dialogOpen = computed({
    get: () => props.isOpen,
    set: (v) => {
        if (!v) emit('close');
    },
});

const checkTypeOptions = [
    { label: 'Criminal Record Check', value: 'criminal_record_check' },
    { label: 'Vulnerable Sector Check', value: 'vulnerable_sector_check' },
    { label: 'Security Clearance', value: 'security_clearance' },
    { label: 'Other', value: 'other' },
];

const statusOptions = [
    { label: 'Pending', value: 'pending' },
    { label: 'Verified', value: 'verified' },
    { label: 'Failed', value: 'failed' },
    { label: 'Expired', value: 'expired' },
];

watch(
    () => [props.isOpen, props.initialData],
    ([open]) => {
        if (!open) return;
        const row = props.initialData || {};
        documentFile.value = null;
        formError.value = '';
        form.value = {
            candidate_name: row?.candidate_name || '',
            check_type: row?.check_type || 'criminal_record_check',
            issue_date: row?.issue_date || '',
            expiry_date: row?.expiry_date || '',
            verification_status: row?.verification_status || 'pending',
            notes: row?.notes || '',
        };
    },
    { immediate: true }
);

function onFileChange(e) {
    documentFile.value = e?.target?.files?.[0] || null;
}

async function submit() {
    try {
        saving.value = true;
        formError.value = '';

        const fd = new FormData();
        fd.append('candidate_name', String(form.value.candidate_name || ''));
        fd.append('check_type', String(form.value.check_type || ''));
        if (form.value.issue_date) fd.append('issue_date', String(form.value.issue_date));
        if (form.value.expiry_date) fd.append('expiry_date', String(form.value.expiry_date));
        if (form.value.verification_status) fd.append('verification_status', String(form.value.verification_status));
        if (form.value.notes) fd.append('notes', String(form.value.notes));

        if (props.attachUserId && props.selectedAdminId) {
            fd.append('user_id', String(props.selectedAdminId));
        }

        if (documentFile.value) {
            fd.append('document', documentFile.value);
        }

        if (!isEdit.value) {
            await axios.post('/api/background-checks', fd, { headers: { 'Content-Type': 'multipart/form-data' } });
        } else {
            fd.append('_method', 'PUT');
            await axios.post(`/api/background-checks/${encodeURIComponent(String(props.initialData.id))}`, fd, {
                headers: { 'Content-Type': 'multipart/form-data' },
            });
        }

        emit('success');
        emit('close');
    } catch (e) {
        formError.value = e?.response?.data?.message || e?.message || 'Failed to save record';
    } finally {
        saving.value = false;
    }
}
</script>

// frontend/components/BackgroundCheckFormModal.tsx
import React, { useEffect, useState } from 'react';
import { X, Upload, Loader2 } from 'lucide-react';

interface BackgroundCheckFormModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess: () => void;
  initialData?: any;
  targetUserId?: string;
  targetUserName?: string;
  request: (endpoint: string, options?: RequestInit) => Promise<any>;
}

const BackgroundCheckFormModal: React.FC<BackgroundCheckFormModalProps> = ({
  isOpen,
  onClose,
  onSuccess,
  initialData,
  targetUserId,
  targetUserName,
  request,
}) => {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [formData, setFormData] = useState({
    candidate_name: initialData?.candidate_name || targetUserName || '',
    check_type: initialData?.check_type || 'criminal_record_check',
    issue_date: initialData?.issue_date || '',
    expiry_date: initialData?.expiry_date || '',
    verification_status: initialData?.verification_status || 'pending',
    notes: initialData?.notes || '',
  });
  const [file, setFile] = useState<File | null>(null);

  useEffect(() => {
    if (!isOpen) return;
    if (initialData?.id) return;
    if (!targetUserName) return;

    setFormData((prev) => ({
      ...prev,
      candidate_name: targetUserName,
    }));
  }, [isOpen, initialData?.id, targetUserName]);

  if (!isOpen) return null;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError('');

    try {
      const data = new FormData();
      Object.entries(formData).forEach(([key, value]) => {
        if (value !== undefined && value !== null) {
          data.append(key, String(value));
        }
      });

      if (!initialData?.id && targetUserId) {
        data.append('user_id', String(targetUserId));
      }

      if (file) {
        data.append('document', file);
      }

      const isEdit = !!initialData?.id;
      const endpoint = isEdit ? `/background-checks/${initialData.id}` : '/background-checks';
      
      if (isEdit) {
        data.append('_method', 'PUT');
      }

      await request(endpoint, {
        method: 'POST',
        body: data,
      });

      onSuccess();
      onClose();
    } catch (err: any) {
      setError(err.message || 'Failed to save background check');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
      <div className="glass-dark w-full max-w-2xl rounded-3xl border border-white/10 shadow-2xl overflow-hidden animate-[fadeInUp_0.3s_ease-out]">
        <div className="flex items-center justify-between p-6 border-b border-white/5">
          <h3 className="font-display text-xl text-white">
            {initialData ? 'Edit Background Check' : 'Add Background Check'}
          </h3>
          <button onClick={onClose} className="text-slate-400 hover:text-white transition-colors">
            <X size={20} />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="p-6 space-y-4">
          {error && (
            <div className="p-4 bg-red-500/10 border border-red-500/20 text-red-400 text-sm rounded-xl">
              {error}
            </div>
          )}

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Field
              label="Admin"
              value={formData.candidate_name}
              onChange={(v) => setFormData({ ...formData, candidate_name: v })}
              required
              readOnly={!initialData?.id && !!targetUserName}
            />
            <div className="space-y-1.5">
              <label className="text-xs font-bold uppercase tracking-widest text-slate-500">Check Type</label>
              <select
                value={formData.check_type}
                onChange={(e) => setFormData({...formData, check_type: e.target.value})}
                className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white focus:outline-none focus:border-primary/50 transition-all appearance-none"
              >
                <option value="criminal_record_check">Criminal Record Check</option>
                <option value="vulnerable_sector_check">Vulnerable Sector Check</option>
                <option value="security_clearance">Security Clearance</option>
                <option value="other">Other</option>
              </select>
            </div>
            <Field label="Issue Date" type="date" value={formData.issue_date} onChange={(v) => setFormData({...formData, issue_date: v})} />
            <Field label="Expiry Date" type="date" value={formData.expiry_date} onChange={(v) => setFormData({...formData, expiry_date: v})} />
            <div className="space-y-1.5">
              <label className="text-xs font-bold uppercase tracking-widest text-slate-500">Status</label>
              <select
                value={formData.verification_status}
                onChange={(e) => setFormData({...formData, verification_status: e.target.value})}
                className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white focus:outline-none focus:border-primary/50 transition-all appearance-none"
              >
                <option value="pending">Pending</option>
                <option value="verified">Verified</option>
                <option value="failed">Failed</option>
                <option value="expired">Expired</option>
              </select>
            </div>
          </div>

          <div className="space-y-1.5">
            <label className="text-xs font-bold uppercase tracking-widest text-slate-500">Notes</label>
            <textarea
              value={formData.notes}
              onChange={(e) => setFormData({...formData, notes: e.target.value})}
              className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white h-24 focus:outline-none focus:border-primary/50 transition-all"
            />
          </div>

          <div className="space-y-2">
            <label className="text-xs font-bold uppercase tracking-widest text-slate-500">Document (PDF/Image)</label>
            <div className="relative">
              <input
                type="file"
                onChange={(e) => setFile(e.target.files?.[0] || null)}
                className="hidden"
                id="bg-file-upload"
                accept=".pdf,.jpg,.jpeg,.png"
              />
              <label
                htmlFor="bg-file-upload"
                className="flex items-center justify-center gap-2 w-full py-4 border-2 border-dashed border-white/10 rounded-2xl cursor-pointer hover:border-primary/50 hover:bg-white/5 transition-all group"
              >
                <Upload size={20} className="text-slate-400 group-hover:text-primary transition-colors" />
                <span className="text-sm text-slate-400 group-hover:text-slate-200">
                  {file ? file.name : (initialData?.document_path ? 'Replace existing document' : 'Upload background check document')}
                </span>
              </label>
            </div>
          </div>

          <div className="flex gap-3 pt-4">
            <button
              type="submit"
              disabled={loading}
              className="flex-1 py-3 rounded-xl bg-primary text-white font-semibold hover:bg-primary/80 transition-all disabled:opacity-50 flex items-center justify-center gap-2"
            >
              {loading && <Loader2 size={18} className="animate-spin" />}
              {initialData ? 'Update Record' : 'Create Record'}
            </button>
            <button
              type="button"
              onClick={onClose}
              className="flex-1 py-3 rounded-xl bg-white/5 border border-white/10 text-slate-200 font-semibold hover:bg-white/10 transition-all"
            >
              Cancel
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

const Field: React.FC<{ label: string; value: string; onChange: (v: string) => void; type?: string; required?: boolean; readOnly?: boolean }> = ({
  label,
  value,
  onChange,
  type = 'text',
  required = false,
  readOnly = false,
}) => (
  <div className="space-y-1.5">
    <label className="text-xs font-bold uppercase tracking-widest text-slate-500">{label}</label>
    <input
      type={type}
      value={value}
      onChange={(e) => onChange(e.target.value)}
      required={required}
      readOnly={readOnly}
      className={`w-full bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white placeholder:text-slate-600 focus:outline-none focus:border-primary/50 transition-all ${readOnly ? 'opacity-80 cursor-not-allowed' : ''}`}
    />
  </div>
);

export default BackgroundCheckFormModal;
