// Agenchq/resources/js/components/dashboard/CredentialFormModal.vue
<template>
  <Dialog
    v-model:visible="dialogOpen"
    modal
    :header="isEdit ? 'Edit Credential' : 'Add New Credential'"
    :style="{ width: 'min(900px, 95vw)' }"
    @hide="emit('close')"
  >
    <form class="space-y-4" @submit.prevent="handleSubmit">
      <Message v-if="error" severity="error" :closable="false">{{ error }}</Message>

      <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div class="space-y-2">
          <label class="text-xs font-bold uppercase tracking-widest text-[color:var(--p-text-muted-color)]">Candidate Name</label>
          <InputText v-model="form.candidate_name" class="w-full" required />
        </div>
        <div class="space-y-2">
          <label class="text-xs font-bold uppercase tracking-widest text-[color:var(--p-text-muted-color)]">Email</label>
          <InputText v-model="form.email" type="email" class="w-full" required />
        </div>
        <div class="space-y-2">
          <label class="text-xs font-bold uppercase tracking-widest text-[color:var(--p-text-muted-color)]">Position</label>
          <InputText v-model="form.position" class="w-full" required />
        </div>
        <div class="space-y-2">
          <label class="text-xs font-bold uppercase tracking-widest text-[color:var(--p-text-muted-color)]">Specialty</label>
          <InputText v-model="form.specialty" class="w-full" />
        </div>
        <div class="space-y-2">
          <label class="text-xs font-bold uppercase tracking-widest text-[color:var(--p-text-muted-color)]">Credential Type</label>
          <Dropdown
            v-model="form.credential_type"
            :options="credentialTypeOptions"
            optionLabel="label"
            optionValue="value"
            filter
            class="w-full"
            placeholder="Select credential"
          />
        </div>
        <div class="space-y-2">
          <label class="text-xs font-bold uppercase tracking-widest text-[color:var(--p-text-muted-color)]">Province</label>
          <InputText v-model="form.province" class="w-full" />
        </div>
        <div class="space-y-2">
          <label class="text-xs font-bold uppercase tracking-widest text-[color:var(--p-text-muted-color)]">Issue Date</label>
          <InputText v-model="form.issue_date" type="date" class="w-full" required />
        </div>
        <div class="space-y-2">
          <label class="text-xs font-bold uppercase tracking-widest text-[color:var(--p-text-muted-color)]">Expiry Date</label>
          <InputText v-model="form.expiry_date" type="date" class="w-full" required />
        </div>
      </div>

      <div class="space-y-2">
        <label class="text-xs font-bold uppercase tracking-widest text-[color:var(--p-text-muted-color)]">Document (PDF/DOC)</label>
        <div class="flex items-center gap-3">
          <input type="file" accept=".pdf,.doc,.docx" @change="onFileChange" />
          <span class="text-sm text-[color:var(--p-text-muted-color)]">{{ fileLabel }}</span>
        </div>
      </div>

      <div class="flex gap-2 justify-end pt-2">
        <Button type="button" label="Cancel" severity="secondary" outlined :disabled="loading" @click="emit('close')" />
        <Button type="submit" :label="isEdit ? 'Update Credential' : 'Create Credential'" :loading="loading" />
      </div>
    </form>
  </Dialog>
</template>

<script setup>
import { computed, ref, watch } from 'vue';
import { apiGet, apiPost, normalizeApiList } from '../../lib/api';
import Button from 'primevue/button';
import Dialog from 'primevue/dialog';
import Dropdown from 'primevue/dropdown';
import InputText from 'primevue/inputtext';
import Message from 'primevue/message';

const props = defineProps({
    isOpen: { type: Boolean, required: true },
    initialData: { type: Object, default: null },
    targetUserId: { type: [String, Number], default: null },
    targetEmail: { type: String, default: '' },
});

const emit = defineEmits(['close', 'success']);

const loading = ref(false);
const error = ref('');
const file = ref(null);

const templates = ref([]);

const credentialTypeOptions = computed(() => {
    const opts = (Array.isArray(templates.value) ? templates.value : [])
        .map((t) => ({
            label: t?.name ? `${t.name} (${t.credential_type})` : String(t?.credential_type || ''),
            value: String(t?.credential_type || '').trim(),
        }))
        .filter((o) => o.value);

    const seen = new Set();
    return opts.filter((o) => {
        const k = o.value.toLowerCase();
        if (seen.has(k)) return false;
        seen.add(k);
        return true;
    });
});

const form = ref({
    candidate_name: '',
    position: '',
    specialty: '',
    credential_type: '',
    email: '',
    issue_date: '',
    expiry_date: '',
    status: 'pending',
    province: '',
});

const isEdit = computed(() => Boolean(props.initialData && props.initialData.id));

const dialogOpen = computed({
    get: () => props.isOpen,
    set: (v) => {
        if (!v) emit('close');
    },
});

const fileLabel = computed(() => {
    if (file.value?.name) return file.value.name;
    if (props.initialData?.document_url) return 'Replace existing document';
    return 'Upload credential document';
});

function hydrate() {
    const d = props.initialData || {};
    form.value = {
        candidate_name: d.candidate_name || '',
        position: d.position || '',
        specialty: d.specialty || '',
        credential_type: d.credential_type || '',
        email: d.email || props.targetEmail || '',
        issue_date: d.issue_date || '',
        expiry_date: d.expiry_date || '',
        status: d.status || 'pending',
        province: d.province || '',
    };
    error.value = '';
    loading.value = false;
    file.value = null;
}

async function loadTemplates() {
    try {
        const res = await apiGet('/templates');
        templates.value = normalizeApiList(res);
    } catch {
        templates.value = [];
    }
}

watch(
    () => [props.isOpen, props.initialData, props.targetEmail],
    ([open]) => {
        if (open) {
            hydrate();
            loadTemplates();
        }
    },
    { immediate: true }
);

function onFileChange(e) {
    file.value = e?.target?.files?.[0] || null;
}

async function handleSubmit() {
    loading.value = true;
    error.value = '';

    try {
        const data = new FormData();
        Object.entries(form.value).forEach(([k, v]) => {
            if (v !== undefined && v !== null) data.append(k, String(v));
        });

        if (!isEdit.value && props.targetUserId) {
            data.append('user_id', String(props.targetUserId));
        }

        if (file.value) {
            data.append('document', file.value);
        }

        const endpoint = isEdit.value ? `/credentials/${encodeURIComponent(String(props.initialData.id))}` : '/credentials';
        if (isEdit.value) data.append('_method', 'PUT');

        await apiPost(endpoint, data);

        emit('success');
        emit('close');
    } catch (e) {
        error.value = e?.response?.data?.message || e?.message || 'Failed to save credential';
    } finally {
        loading.value = false;
    }
}
</script>

// frontend/components/CredentialFormModal.tsx
import React, { useState } from 'react';
import { X, Upload, Loader2 } from 'lucide-react';

interface CredentialFormModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess: () => void;
  initialData?: any;
  targetUserId?: string;
  targetEmail?: string;
  request: (endpoint: string, options?: RequestInit) => Promise<any>;
}

const CredentialFormModal: React.FC<CredentialFormModalProps> = ({
  isOpen,
  onClose,
  onSuccess,
  initialData,
  targetUserId,
  targetEmail,
  request,
}) => {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [formData, setFormData] = useState({
    candidate_name: initialData?.candidate_name || '',
    position: initialData?.position || '',
    specialty: initialData?.specialty || '',
    credential_type: initialData?.credential_type || '',
    email: initialData?.email || targetEmail || '',
    issue_date: initialData?.issue_date || '',
    expiry_date: initialData?.expiry_date || '',
    status: initialData?.status || 'pending',
    province: initialData?.province || '',
  });
  const [file, setFile] = useState<File | null>(null);

  if (!isOpen) return null;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError('');

    try {
      const data = new FormData();
      Object.entries(formData).forEach(([key, value]) => {
        if (value !== undefined && value !== null) {
          data.append(key, String(value) as string); // explicitly cast to string
        }
      });

      // When creating a credential from OrgUsers context, allow admins to attach it to that user.
      // Backend must enforce org scoping + role permissions.
      if (!initialData?.id && targetUserId) {
        data.append('user_id', String(targetUserId));
      }

      if (file) {
        data.append('document', file);
      }

      const isEdit = !!initialData?.id;
      const endpoint = isEdit ? `/credentials/${initialData.id}` : '/credentials';
      const method = isEdit ? 'POST' : 'POST'; // Laravel often requires POST with _method=PUT for FormData
      
      if (isEdit) {
        data.append('_method', 'PUT');
      }

      await request(endpoint, {
        method,
        body: data,
        // useApi will handle Authorization header, but we must NOT set Content-Type header manually for FormData
      });

      onSuccess();
      onClose();
    } catch (err: any) {
      setError(err.message || 'Failed to save credential');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
      <div className="glass-dark w-full max-w-2xl rounded-3xl border border-white/10 shadow-2xl overflow-hidden animate-[fadeInUp_0.3s_ease-out]">
        <div className="flex items-center justify-between p-6 border-b border-white/5">
          <h3 className="font-display text-xl text-white">
            {initialData ? 'Edit Credential' : 'Add New Credential'}
          </h3>
          <button onClick={onClose} className="text-slate-400 hover:text-white transition-colors">
            <X size={20} />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="p-6 space-y-4">
          {error && (
            <div className="p-4 bg-red-500/10 border border-red-500/20 text-red-400 text-sm rounded-xl">
              {error}
            </div>
          )}

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Field label="Candidate Name" value={formData.candidate_name} onChange={(v) => setFormData({...formData, candidate_name: v})} required />
            <Field label="Email" type="email" value={formData.email} onChange={(v) => setFormData({...formData, email: v})} required />
            <Field label="Position" value={formData.position} onChange={(v) => setFormData({...formData, position: v})} required />
            <Field label="Specialty" value={formData.specialty} onChange={(v) => setFormData({...formData, specialty: v})} />
            <Field label="Credential Type" value={formData.credential_type} onChange={(v) => setFormData({...formData, credential_type: v})} required />
            <Field label="Province" value={formData.province} onChange={(v) => setFormData({...formData, province: v})} />
            <Field label="Issue Date" type="date" value={formData.issue_date} onChange={(v) => setFormData({...formData, issue_date: v})} required />
            <Field label="Expiry Date" type="date" value={formData.expiry_date} onChange={(v) => setFormData({...formData, expiry_date: v})} required />
          </div>

          <div className="space-y-2">
            <label className="text-xs font-bold uppercase tracking-widest text-slate-500">Document (PDF/DOC)</label>
            <div className="relative">
              <input
                type="file"
                onChange={(e) => setFile(e.target.files?.[0] || null)}
                className="hidden"
                id="file-upload"
                accept=".pdf,.doc,.docx"
              />
              <label
                htmlFor="file-upload"
                className="flex items-center justify-center gap-2 w-full py-4 border-2 border-dashed border-white/10 rounded-2xl cursor-pointer hover:border-primary/50 hover:bg-white/5 transition-all group"
              >
                <Upload size={20} className="text-slate-400 group-hover:text-primary transition-colors" />
                <span className="text-sm text-slate-400 group-hover:text-slate-200">
                  {file ? file.name : (initialData?.document_url ? 'Replace existing document' : 'Upload credential document')}
                </span>
              </label>
            </div>
          </div>

          <div className="flex gap-3 pt-4">
            <button
              type="submit"
              disabled={loading}
              className="flex-1 py-3 rounded-xl bg-primary text-white font-semibold hover:bg-primary/80 transition-all disabled:opacity-50 flex items-center justify-center gap-2"
            >
              {loading && <Loader2 size={18} className="animate-spin" />}
              {initialData ? 'Update Credential' : 'Create Credential'}
            </button>
            <button
              type="button"
              onClick={onClose}
              className="flex-1 py-3 rounded-xl bg-white/5 border border-white/10 text-slate-200 font-semibold hover:bg-white/10 transition-all"
            >
              Cancel
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

const Field: React.FC<{ label: string; value: string; onChange: (v: string) => void; type?: string; required?: boolean }> = ({
  label,
  value,
  onChange,
  type = 'text',
  required = false,
}) => (
  <div className="space-y-1.5">
    <label className="text-xs font-bold uppercase tracking-widest text-slate-500">{label}</label>
    <input
      type={type}
      value={value}
      onChange={(e) => onChange(e.target.value)}
      required={required}
      className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-2.5 text-sm text-white placeholder:text-slate-600 focus:outline-none focus:border-primary/50 transition-all"
    />
  </div>
);

export default CredentialFormModal;
